version: "3"

services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    volumes:
      - "./volumes/jenkins:/var/jenkins_home"
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - network

  sonar:
    image: sonarqube
    container_name: sonar
    volumes:
      - "./volumes/sonar/data:/opt/sonarqube/data"
      - "./volumes/sonar/logs:/opt/sonarqube/logs"
    ports:
      - "9000:9000"
    networks:
      - network

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    volumes:
      - "./volumes/nexus:/nexus-data"
    ports:
      - "8081:8081"
    networks:
      - network

  tomcat:
    image: tomcat
    container_name: tomcat
    volumes:
      - "./volumes/tomcat/logs:/usr/local/tomcat/logs"
      - "./volumes/tomcat/conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml"
      - "./volumes/tomcat/conf/Catalina:/usr/local/tomcat/conf/Catalina"
    ports:
      - "8083:8080"
    networks:
      - network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - "./volumes/nginx/html:/usr/share/nginx/html"
      - "./volumes/nginx/etc/nginx.conf:/etc/nginx/nginx.conf"
      - "./volumes/nginx/etc/conf.d:/etc/nginx/conf.d"
      - "./volumes/nginx/log:/var/log/nginx"
    ports:
      - "8084:80"
    networks:
      - network

  serveo:
    build: ./dockerfiles/alpinewithopenssh
    image: alpinewithopenssh:latest
    container_name: serveo
    tty: true
    stdin_open: true
    command: "ssh -R 80:nginx:80 -o \"TCPKeepAlive yes\" -o \"ServerAliveInterval 30\" -o \"StrictHostKeyChecking no\" serveo.net"
    networks:
      - network
   
volumes:
  data-volume:

networks:
  network: